
import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'sw' | 'fr' | 'es' | 'zh' | 'de';

interface LanguageContextType {
  currentLanguage: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

const translations = {
  en: {
    // Header
    home: "Home",
    about: "About",
    services: "Services",
    contact: "Contact",
    languages: "Languages",
    
    // Languages
    english: "English",
    kiswahili: "Kiswahili",
    french: "French",
    spanish: "Spanish",
    mandarin: "Mandarin",
    german: "German",
    
    // Hero
    heroTitle: "Anna & Co Advocates",
    heroSubtitle: "Professional Legal Services",
    heroDescription: "Your trusted legal partners providing comprehensive representation across all areas of law. From corporate matters to personal legal needs, we deliver professional excellence with integrity and dedication.",
    scheduleConsultation: "Schedule Consultation",
    learnMore: "Learn More",
    
    // About
    aboutTitle: "About Anna & Co Advocates",
    aboutSubtitle: "A distinguished legal practice committed to delivering exceptional legal services with unwavering professionalism",
    managingDirectorQuote: "At Anna & Co Advocates, we understand that legal challenges can be overwhelming. That's why we're committed to providing not just expert legal representation, but also the personal attention and clear communication you deserve. Every client matters, every case is important, and every detail receives our full professional dedication. Trust us to stand with you through your legal journey.",
    managingDirector: "Managing Director",
    excellenceTitle: "Excellence in Legal Practice",
    excellenceDescription1: "Anna & Co Advocates stands as a beacon of legal excellence, providing comprehensive legal services across diverse practice areas. Our commitment to professional integrity, meticulous attention to detail, and client-centered approach sets us apart in the legal landscape.",
    excellenceDescription2: "We understand that legal matters require not just expertise, but also empathy and clear communication. Our approach ensures that every client receives personalized attention and strategic guidance tailored to their unique circumstances.",
    foundationTitle: "Our Foundation",
    professionalExcellence: "Professional Excellence",
    integrity: "Integrity",
    clientFocus: "Client Focus",
    innovation: "Innovation",
    resultsDriven: "Results-Driven",
    credentialsTitle: "Professional Credentials",
    llbDegree: "Bachelor of Laws (LLB)",
    legalEducation: "Comprehensive legal education",
    graduated: "Graduated with distinction",
    admittedBar: "Admitted to the Bar",
    licensedPractitioner: "Licensed Legal Practitioner",
    kenyaSchoolLaw: "Kenya School of Law",
    verification: "Verification",
    verifyCredentials: "Verify credentials at Kenya School of Law",
    approachTitle: "Our Approach",
    approach1: "Comprehensive legal analysis and strategy",
    approach2: "Transparent communication at every step",
    approach3: "Tailored solutions for each client's needs",
    approach4: "Modern practice with time-tested principles",
    
    // Services
    servicesTitle: "Legal Services",
    servicesSubtitle: "Comprehensive legal representation across multiple practice areas with professional excellence and personalized attention",
    corporateLaw: "Corporate Law",
    corporateDescription: "Comprehensive business legal services including formation, governance, and compliance matters.",
    businessRegistration: "Business Registration",
    corporateGovernance: "Corporate Governance",
    complianceAdvisory: "Compliance Advisory",
    commercialContracts: "Commercial Contracts",
    contractLaw: "Contract Law",
    contractDescription: "Expert contract services from drafting to dispute resolution across all industries.",
    contractDrafting: "Contract Drafting",
    agreementReview: "Agreement Review",
    negotiationSupport: "Negotiation Support",
    breachResolution: "Breach Resolution",
    civilLitigation: "Civil Litigation",
    litigationDescription: "Strategic litigation services with thorough preparation and skilled courtroom advocacy.",
    courtRepresentation: "Court Representation",
    caseStrategy: "Case Strategy",
    settlementNegotiation: "Settlement Negotiation",
    appealsProcess: "Appeals Process",
    familyLaw: "Family Law",
    familyDescription: "Compassionate legal support for family matters with sensitivity and expertise.",
    divorceProceedings: "Divorce Proceedings",
    childCustody: "Child Custody",
    matrimonialProperty: "Matrimonial Property",
    familyMediation: "Family Mediation",
    landPropertyLaw: "Land & Property Law",
    propertyDescription: "Comprehensive property legal services including transactions, disputes, and title matters.",
    propertyTransactions: "Property Transactions",
    titleVerification: "Title Verification",
    landDisputes: "Land Disputes",
    conveyancing: "Conveyancing",
    countyNationalLaw: "County & National Legal Matters",
    governmentDescription: "Specialized representation in government and administrative legal proceedings.",
    administrativeLaw: "Administrative Law",
    governmentRelations: "Government Relations",
    publicPolicy: "Public Policy",
    regulatoryCompliance: "Regulatory Compliance",
    keyServices: "Key Services:",
    specializedConsultation: "Need legal assistance in a specialized area? We provide consultation across various fields of law.",
    discussLegalNeeds: "Discuss Your Legal Needs",
    
    // Contact
    contactTitle: "Contact Us",
    contactSubtitle: "Get in touch with Anna & Co Advocates for professional legal consultation",
    getInTouch: "Get In Touch",
    contactDescription: "Ready to discuss your legal needs? Contact Anna & Co Advocates today for professional legal consultation and representation.",
    phone: "Phone",
    email: "Email",
    location: "Location",
    locationValue: "Nairobi CBD, Kenya",
    officeHours: "Office Hours",
    mondayFriday: "Monday - Friday: 8:00 AM - 6:00 PM",
    saturday: "Saturday: 9:00 AM - 2:00 PM",
    sunday: "Sunday: By Appointment",
    
    // Footer
    practiceAreas: "Practice Areas",
    allRightsReserved: "All rights reserved.",
    legalDisclaimer: "This website does not constitute legal advice. Professional consultation required for legal guidance.",
  },
  
  sw: {
    // Header
    home: "Nyumbani",
    about: "Kuhusu",
    services: "Huduma",
    contact: "Mawasiliano",
    languages: "Lugha",
    
    // Languages
    english: "Kiingereza",
    kiswahili: "Kiswahili",
    french: "Kifaransa",
    spanish: "Kihispania",
    mandarin: "Kichina",
    german: "Kijerumani",
    
    // Hero
    heroTitle: "Anna & Co Advocates",
    heroSubtitle: "Huduma za Kisheria za Kitaalamu",
    heroDescription: "Washirika wako wa kuaminika wa kisheria wanaotoa uwakilishi wa kina katika maeneo yote ya sheria. Kutoka mambo ya makampuni hadi mahitaji ya kibinafsi ya kisheria, tunatoa ubora wa kitaalamu kwa uongozi na kujitolea.",
    scheduleConsultation: "Panga Mazungumzo",
    learnMore: "Jifunze Zaidi",
    
    // About
    aboutTitle: "Kuhusu Anna & Co Advocates",
    aboutSubtitle: "Shirika la heshima la kisheria lililojitolea kutoa huduma bora za kisheria kwa utaalamu usio na upungufu",
    managingDirectorQuote: "Katika Anna & Co Advocates, tunaelewa kuwa changamoto za kisheria zinaweza kuwa za kushinda. Ndiyo maana tumejitolea kutoa si tu uwakilishi bora wa kisheria, lakini pia umakini binafsi na mawasiliano wazi mnayostahili. Kila mteja ni muhimu, kila kesi ni muhimu, na kila undani unapokea kujitolea kwetu kamili kwa kitaalamu. Tuaminini tutasimama pamoja nanyi katika safari yenu ya kisheria.",
    managingDirector: "Mkurugenzi Mkuu",
    excellenceTitle: "Ubora katika Mazoezi ya Kisheria",
    excellenceDescription1: "Anna & Co Advocates inasimama kama mwanga wa ubora wa kisheria, ikitoa huduma kamili za kisheria katika maeneo mbalimbali ya mazoezi. Kujitolea kwetu kwa uongozi wa kitaalamu, umakini wa kina, na mkabala unaowalenga wateja ndio unaotufanya kuwa tofauti katika mazingira ya kisheria.",
    excellenceDescription2: "Tunaelewa kuwa mambo ya kisheria yanahitaji si tu utaalamu, lakini pia huruma na mawasiliano wazi. Mbinu yetu inahakikisha kuwa kila mteja anapokea umakini binafsi na mwongozo wa kimkakati unaofaa mazingira yake ya kipekee.",
    foundationTitle: "Msingi Wetu",
    professionalExcellence: "Ubora wa Kitaalamu",
    integrity: "Uongozi",
    clientFocus: "Umakini wa Mteja",
    innovation: "Uvumbuzi",
    resultsDriven: "Uongozwa na Matokeo",
    credentialsTitle: "Vyeti vya Kitaalamu",
    llbDegree: "Shahada ya Sheria (LLB)",
    legalEducation: "Elimu kamili ya kisheria",
    graduated: "Alihitimu kwa heshima",
    admittedBar: "Amekubaliwa katika Baa",
    licensedPractitioner: "Mfanyakazi wa Kisheria Aliyeidhinishwa",
    kenyaSchoolLaw: "Shule ya Sheria ya Kenya",
    verification: "Uthibitisho",
    verifyCredentials: "Thibitisha vyeti katika Shule ya Sheria ya Kenya",
    approachTitle: "Mbinu Yetu",
    approach1: "Uchambuzi kamili wa kisheria na mkakati",
    approach2: "Mawasiliano wazi katika kila hatua",
    approach3: "Ufumbuzi unaobinafsishwa kwa mahitaji ya kila mteja",
    approach4: "Mazoezi ya kisasa na kanuni za zamani za mtihani",
    
    // Services
    servicesTitle: "Huduma za Kisheria",
    servicesSubtitle: "Uwakilishi kamili wa kisheria katika maeneo mengi ya mazoezi kwa ubora wa kitaalamu na umakini wa kibinafsi",
    corporateLaw: "Sheria za Makampuni",
    corporateDescription: "Huduma kamili za kisheria za biashara ikiwa ni pamoja na uundaji, utawala, na mambo ya kufuata sheria.",
    businessRegistration: "Usajili wa Biashara",
    corporateGovernance: "Utawala wa Makampuni",
    complianceAdvisory: "Ushauri wa Kufuata Sheria",
    commercialContracts: "Mikataba ya Kibiashara",
    contractLaw: "Sheria za Mikataba",
    contractDescription: "Huduma za mtaalamu za mikataba kutoka uandishi hadi ufumbuzi wa migogoro katika viwanda vyote.",
    contractDrafting: "Uandishi wa Mikataba",
    agreementReview: "Ukaguzi wa Makubaliano",
    negotiationSupport: "Msaada wa Mazungumzo",
    breachResolution: "Ufumbuzi wa Ukiukaji",
    civilLitigation: "Ushtaki wa Kiraia",
    litigationDescription: "Huduma za ushtaki wa kimkakati na maandalizi ya kina na utetezi mahiri wa korti.",
    courtRepresentation: "Uwakilishi wa Korti",
    caseStrategy: "Mkakati wa Kesi",
    settlementNegotiation: "Mazungumzo ya Makubaliano",
    appealsProcess: "Mchakato wa Rufaa",
    familyLaw: "Sheria za Familia",
    familyDescription: "Msaada wa kisheria wa huruma kwa mambo ya familia kwa unyeti na utaalamu.",
    divorceProceedings: "Michakato ya Talaka",
    childCustody: "Ulinzi wa Watoto",
    matrimonialProperty: "Mali ya Ndoa",
    familyMediation: "Upatanisho wa Familia",
    landPropertyLaw: "Sheria za Ardhi na Mali",
    propertyDescription: "Huduma kamili za kisheria za mali ikiwa ni pamoja na miamala, migogoro, na mambo ya hati.",
    propertyTransactions: "Miamala ya Mali",
    titleVerification: "Uthibitisho wa Hati",
    landDisputes: "Migogoro ya Ardhi",
    conveyancing: "Uhamishaji wa Mali",
    countyNationalLaw: "Mambo ya Kisheria ya Kaunti na Kitaifa",
    governmentDescription: "Uwakilishi maalum katika michakato ya kisheria ya serikali na utawala.",
    administrativeLaw: "Sheria za Utawala",
    governmentRelations: "Mahusiano ya Serikali",
    publicPolicy: "Sera za Umma",
    regulatoryCompliance: "Kufuata Kanuni",
    keyServices: "Huduma Kuu:",
    specializedConsultation: "Unahitaji msaada wa kisheria katika eneo maalum? Tunatoa ushauri katika nyanja mbalimbali za sheria.",
    discussLegalNeeds: "Jadili Mahitaji Yako ya Kisheria",
    
    // Contact
    contactTitle: "Wasiliana Nasi",
    contactSubtitle: "Wasiliana na Anna & Co Advocates kwa ushauri wa kitaalamu wa kisheria",
    getInTouch: "Wasiliana",
    contactDescription: "Uko tayari kujadili mahitaji yako ya kisheria? Wasiliana na Anna & Co Advocates leo kwa ushauri wa kitaalamu wa kisheria na uwakilishi.",
    phone: "Simu",
    email: "Barua Pepe",
    location: "Mahali",
    locationValue: "Nairobi CBD, Kenya",
    officeHours: "Masaa ya Ofisi",
    mondayFriday: "Jumatatu - Ijumaa: 8:00 AM - 6:00 PM",
    saturday: "Jumamosi: 9:00 AM - 2:00 PM",
    sunday: "Jumapili: Kwa Miadi",
    
    // Footer
    practiceAreas: "Maeneo ya Mazoezi",
    allRightsReserved: "Haki zote zimehifadhiwa.",
    legalDisclaimer: "Tovuti hii haifanyi ushauri wa kisheria. Mazungumzo ya kitaalamu yanahitajika kwa mwongozo wa kisheria.",
  },
  
  fr: {
    // Header
    home: "Accueil",
    about: "À propos",
    services: "Services",
    contact: "Contact",
    languages: "Langues",
    
    // Languages
    english: "Anglais",
    kiswahili: "Kiswahili",
    french: "Français",
    spanish: "Espagnol",
    mandarin: "Mandarin",
    german: "Allemand",
    
    // Hero
    heroTitle: "Anna & Co Advocates",
    heroSubtitle: "Services Juridiques Professionnels",
    heroDescription: "Vos partenaires juridiques de confiance offrant une représentation complète dans tous les domaines du droit. Des affaires d'entreprise aux besoins juridiques personnels, nous offrons l'excellence professionnelle avec intégrité et dévouement.",
    scheduleConsultation: "Programmer une Consultation",
    learnMore: "En Savoir Plus",
    
    // About
    aboutTitle: "À propos d'Anna & Co Advocates",
    aboutSubtitle: "Un cabinet juridique distingué engagé à fournir des services juridiques exceptionnels avec un professionnalisme inébranlable",
    managingDirectorQuote: "Chez Anna & Co Advocates, nous comprenons que les défis juridiques peuvent être accablants. C'est pourquoi nous nous engageons à fournir non seulement une représentation juridique experte, mais aussi l'attention personnelle et la communication claire que vous méritez. Chaque client compte, chaque cas est important, et chaque détail reçoit notre dévouement professionnel complet. Faites-nous confiance pour vous accompagner dans votre parcours juridique.",
    managingDirector: "Directrice Générale",
    excellenceTitle: "Excellence en Pratique Juridique",
    excellenceDescription1: "Anna & Co Advocates se dresse comme un phare d'excellence juridique, fournissant des services juridiques complets dans divers domaines de pratique. Notre engagement envers l'intégrité professionnelle, l'attention méticuleuse aux détails et l'approche centrée sur le client nous distingue dans le paysage juridique.",
    excellenceDescription2: "Nous comprenons que les questions juridiques nécessitent non seulement une expertise, mais aussi de l'empathie et une communication claire. Notre approche garantit que chaque client reçoit une attention personnalisée et des conseils stratégiques adaptés à ses circonstances uniques.",
    foundationTitle: "Notre Fondation",
    professionalExcellence: "Excellence Professionnelle",
    integrity: "Intégrité",
    clientFocus: "Focus Client",
    innovation: "Innovation",
    resultsDriven: "Orienté Résultats",
    credentialsTitle: "Qualifications Professionnelles",
    llbDegree: "Licence en Droit (LLB)",
    legalEducation: "Formation juridique complète",
    graduated: "Diplômé avec distinction",
    admittedBar: "Admis au Barreau",
    licensedPractitioner: "Praticien Juridique Agréé",
    kenyaSchoolLaw: "École de Droit du Kenya",
    verification: "Vérification",
    verifyCredentials: "Vérifier les qualifications à l'École de Droit du Kenya",
    approachTitle: "Notre Approche",
    approach1: "Analyse juridique et stratégie complètes",
    approach2: "Communication transparente à chaque étape",
    approach3: "Solutions sur mesure pour les besoins de chaque client",
    approach4: "Pratique moderne avec des principes éprouvés",
    
    // Services
    servicesTitle: "Services Juridiques",
    servicesSubtitle: "Représentation juridique complète dans plusieurs domaines de pratique avec excellence professionnelle et attention personnalisée",
    corporateLaw: "Droit des Sociétés",
    corporateDescription: "Services juridiques d'entreprise complets incluant la formation, la gouvernance et les questions de conformité.",
    businessRegistration: "Enregistrement d'Entreprise",
    corporateGovernance: "Gouvernance d'Entreprise",
    complianceAdvisory: "Conseil en Conformité",
    commercialContracts: "Contrats Commerciaux",
    contractLaw: "Droit des Contrats",
    contractDescription: "Services contractuels experts de la rédaction à la résolution des litiges dans toutes les industries.",
    contractDrafting: "Rédaction de Contrats",
    agreementReview: "Révision d'Accords",
    negotiationSupport: "Support de Négociation",
    breachResolution: "Résolution de Violations",
    civilLitigation: "Litiges Civils",
    litigationDescription: "Services de litiges stratégiques avec préparation minutieuse et plaidoirie compétente.",
    courtRepresentation: "Représentation en Cour",
    caseStrategy: "Stratégie de Cas",
    settlementNegotiation: "Négociation de Règlement",
    appealsProcess: "Processus d'Appel",
    familyLaw: "Droit de la Famille",
    familyDescription: "Support juridique compatissant pour les questions familiales avec sensibilité et expertise.",
    divorceProceedings: "Procédures de Divorce",
    childCustody: "Garde d'Enfants",
    matrimonialProperty: "Propriété Matrimoniale",
    familyMediation: "Médiation Familiale",
    landPropertyLaw: "Droit des Terres et Propriétés",
    propertyDescription: "Services juridiques immobiliers complets incluant transactions, litiges et questions de titre.",
    propertyTransactions: "Transactions Immobilières",
    titleVerification: "Vérification de Titre",
    landDisputes: "Litiges Fonciers",
    conveyancing: "Transfert de Propriété",
    countyNationalLaw: "Questions Juridiques Régionales et Nationales",
    governmentDescription: "Représentation spécialisée dans les procédures juridiques gouvernementales et administratives.",
    administrativeLaw: "Droit Administratif",
    governmentRelations: "Relations Gouvernementales",
    publicPolicy: "Politique Publique",
    regulatoryCompliance: "Conformité Réglementaire",
    keyServices: "Services Clés:",
    specializedConsultation: "Besoin d'assistance juridique dans un domaine spécialisé? Nous fournissons des consultations dans divers domaines du droit.",
    discussLegalNeeds: "Discuter de Vos Besoins Juridiques",
    
    // Contact
    contactTitle: "Nous Contacter",
    contactSubtitle: "Contactez Anna & Co Advocates pour une consultation juridique professionnelle",
    getInTouch: "Prendre Contact",
    contactDescription: "Prêt à discuter de vos besoins juridiques? Contactez Anna & Co Advocates aujourd'hui pour une consultation et représentation juridique professionnelle.",
    phone: "Téléphone",
    email: "Email",
    location: "Localisation",
    locationValue: "Nairobi CBD, Kenya",
    officeHours: "Heures de Bureau",
    mondayFriday: "Lundi - Vendredi: 8:00 AM - 6:00 PM",
    saturday: "Samedi: 9:00 AM - 2:00 PM",
    sunday: "Dimanche: Sur Rendez-vous",
    
    // Footer
    practiceAreas: "Domaines de Pratique",
    allRightsReserved: "Tous droits réservés.",
    legalDisclaimer: "Ce site web ne constitue pas un conseil juridique. Une consultation professionnelle est requise pour des conseils juridiques.",
  },
  
  es: {
    // Header
    home: "Inicio",
    about: "Acerca de",
    services: "Servicios",
    contact: "Contacto",
    languages: "Idiomas",
    
    // Languages
    english: "Inglés",
    kiswahili: "Kiswahili",
    french: "Francés",
    spanish: "Español",
    mandarin: "Mandarín",
    german: "Alemán",
    
    // Hero
    heroTitle: "Anna & Co Advocates",
    heroSubtitle: "Servicios Legales Profesionales",
    heroDescription: "Sus socios legales de confianza que brindan representación integral en todas las áreas del derecho. Desde asuntos corporativos hasta necesidades legales personales, ofrecemos excelencia profesional con integridad y dedicación.",
    scheduleConsultation: "Programar Consulta",
    learnMore: "Saber Más",
    
    // About
    aboutTitle: "Acerca de Anna & Co Advocates",
    aboutSubtitle: "Un prestigioso bufete legal comprometido a brindar servicios legales excepcionales con profesionalismo inquebrantable",
    managingDirectorQuote: "En Anna & Co Advocates, entendemos que los desafíos legales pueden ser abrumadores. Por eso nos comprometemos a brindar no solo representación legal experta, sino también la atención personal y comunicación clara que usted merece. Cada cliente importa, cada caso es importante, y cada detalle recibe nuestra dedicación profesional completa. Confíe en nosotros para acompañarlo en su camino legal.",
    managingDirector: "Directora General",
    excellenceTitle: "Excelencia en la Práctica Legal",
    excellenceDescription1: "Anna & Co Advocates se erige como un faro de excelencia legal, brindando servicios legales integrales en diversas áreas de práctica. Nuestro compromiso con la integridad profesional, atención meticulosa al detalle y enfoque centrado en el cliente nos distingue en el panorama legal.",
    excellenceDescription2: "Entendemos que los asuntos legales requieren no solo experiencia, sino también empatía y comunicación clara. Nuestro enfoque asegura que cada cliente reciba atención personalizada y orientación estratégica adaptada a sus circunstancias únicas.",
    foundationTitle: "Nuestra Base",
    professionalExcellence: "Excelencia Profesional",
    integrity: "Integridad",
    clientFocus: "Enfoque al Cliente",
    innovation: "Innovación",
    resultsDriven: "Orientado a Resultados",
    credentialsTitle: "Credenciales Profesionales",
    llbDegree: "Licenciatura en Derecho (LLB)",
    legalEducation: "Educación legal integral",
    graduated: "Graduado con distinción",
    admittedBar: "Admitido en el Colegio de Abogados",
    licensedPractitioner: "Profesional Legal Licenciado",
    kenyaSchoolLaw: "Escuela de Derecho de Kenia",
    verification: "Verificación",
    verifyCredentials: "Verificar credenciales en la Escuela de Derecho de Kenia",
    approachTitle: "Nuestro Enfoque",
    approach1: "Análisis legal integral y estrategia",
    approach2: "Comunicación transparente en cada paso",
    approach3: "Soluciones personalizadas para las necesidades de cada cliente",
    approach4: "Práctica moderna con principios probados",
    
    // Services
    servicesTitle: "Servicios Legales",
    servicesSubtitle: "Representación legal integral en múltiples áreas de práctica con excelencia profesional y atención personalizada",
    corporateLaw: "Derecho Corporativo",
    corporateDescription: "Servicios legales empresariales integrales incluyendo formación, gobernanza y asuntos de cumplimiento.",
    businessRegistration: "Registro de Negocios",
    corporateGovernance: "Gobernanza Corporativa",
    complianceAdvisory: "Asesoría de Cumplimiento",
    commercialContracts: "Contratos Comerciales",
    contractLaw: "Derecho de Contratos",
    contractDescription: "Servicios contractuales expertos desde redacción hasta resolución de disputas en todas las industrias.",
    contractDrafting: "Redacción de Contratos",
    agreementReview: "Revisión de Acuerdos",
    negotiationSupport: "Apoyo en Negociación",
    breachResolution: "Resolución de Incumplimientos",
    civilLitigation: "Litigio Civil",
    litigationDescription: "Servicios de litigio estratégico con preparación minuciosa y defensa hábil en el tribunal.",
    courtRepresentation: "Representación en Tribunal",
    caseStrategy: "Estrategia de Caso",
    settlementNegotiation: "Negociación de Acuerdo",
    appealsProcess: "Proceso de Apelaciones",
    familyLaw: "Derecho de Familia",
    familyDescription: "Apoyo legal compasivo para asuntos familiares con sensibilidad y experiencia.",
    divorceProceedings: "Procedimientos de Divorcio",
    childCustody: "Custodia de Menores",
    matrimonialProperty: "Propiedad Matrimonial",
    familyMediation: "Mediación Familiar",
    landPropertyLaw: "Derecho de Tierras y Propiedades",
    propertyDescription: "Servicios legales inmobiliarios integrales incluyendo transacciones, disputas y asuntos de títulos.",
    propertyTransactions: "Transacciones de Propiedad",
    titleVerification: "Verificación de Títulos",
    landDisputes: "Disputas de Tierras",
    conveyancing: "Transferencia de Propiedades",
    countyNationalLaw: "Asuntos Legales Regionales y Nacionales",
    governmentDescription: "Representación especializada en procedimientos legales gubernamentales y administrativos.",
    administrativeLaw: "Derecho Administrativo",
    governmentRelations: "Relaciones Gubernamentales",
    publicPolicy: "Política Pública",
    regulatoryCompliance: "Cumplimiento Regulatorio",
    keyServices: "Servicios Clave:",
    specializedConsultation: "¿Necesita asistencia legal en un área especializada? Proporcionamos consultas en varios campos del derecho.",
    discussLegalNeeds: "Discuta Sus Necesidades Legales",
    
    // Contact
    contactTitle: "Contáctanos",
    contactSubtitle: "Póngase en contacto con Anna & Co Advocates para consulta legal profesional",
    getInTouch: "Ponerse en Contacto",
    contactDescription: "¿Listo para discutir sus necesidades legales? Contacte a Anna & Co Advocates hoy para consulta y representación legal profesional.",
    phone: "Teléfono",
    email: "Correo Electrónico",
    location: "Ubicación",
    locationValue: "Nairobi CBD, Kenia",
    officeHours: "Horario de Oficina",
    mondayFriday: "Lunes - Viernes: 8:00 AM - 6:00 PM",
    saturday: "Sábado: 9:00 AM - 2:00 PM",
    sunday: "Domingo: Con Cita Previa",
    
    // Footer
    practiceAreas: "Áreas de Práctica",
    allRightsReserved: "Todos los derechos reservados.",
    legalDisclaimer: "Este sitio web no constituye asesoramiento legal. Se requiere consulta profesional para orientación legal.",
  },
  
  zh: {
    // Header
    home: "首页",
    about: "关于我们",
    services: "服务",
    contact: "联系我们",
    languages: "语言",
    
    // Languages
    english: "英语",
    kiswahili: "斯瓦希里语",
    french: "法语",
    spanish: "西班牙语",
    mandarin: "中文",
    german: "德语",
    
    // Hero
    heroTitle: "Anna & Co Advocates",
    heroSubtitle: "专业法律服务",
    heroDescription: "您值得信赖的法律合作伙伴，为您提供所有法律领域的全面代理服务。从企业事务到个人法律需求，我们以诚信和奉献精神提供专业卓越的服务。",
    scheduleConsultation: "预约咨询",
    learnMore: "了解更多",
    
    // About
    aboutTitle: "关于 Anna & Co Advocates",
    aboutSubtitle: "一家杰出的律师事务所，致力于以坚定不移的专业精神提供卓越的法律服务",
    managingDirectorQuote: "在 Anna & Co Advocates，我们理解法律挑战可能令人不知所措。这就是为什么我们致力于不仅提供专业的法律代理，还提供您应得的个人关注和清晰沟通。每个客户都很重要，每个案件都很重要，每个细节都得到我们全面的专业奉献。请相信我们陪伴您走过法律之路。",
    managingDirector: "总经理",
    excellenceTitle: "法律实践中的卓越",
    excellenceDescription1: "Anna & Co Advocates 作为法律卓越的灯塔，在各种实践领域提供全面的法律服务。我们对专业诚信、细致入微的关注和以客户为中心的方法的承诺使我们在法律领域中脱颖而出。",
    excellenceDescription2: "我们理解法律事务不仅需要专业知识，还需要同理心和清晰的沟通。我们的方法确保每个客户都能获得个性化的关注和针对其独特情况的战略指导。",
    foundationTitle: "我们的基础",
    professionalExcellence: "专业卓越",
    integrity: "诚信",
    clientFocus: "客户为本",
    innovation: "创新",
    resultsDriven: "结果导向",
    credentialsTitle: "专业资质",
    llbDegree: "法学学士 (LLB)",
    legalEducation: "全面的法律教育",
    graduated: "优异成绩毕业",
    admittedBar: "获准执业",
    licensedPractitioner: "持证法律从业者",
    kenyaSchoolLaw: "肯尼亚法学院",
    verification: "验证",
    verifyCredentials: "在肯尼亚法学院验证资质",
    approachTitle: "我们的方法",
    approach1: "全面的法律分析和策略",
    approach2: "每个步骤的透明沟通",
    approach3: "为每个客户需求量身定制的解决方案",
    approach4: "现代实践与经过时间考验的原则",
    
    // Services
    servicesTitle: "法律服务",
    servicesSubtitle: "多个实践领域的全面法律代理，具有专业卓越和个性化关注",
    corporateLaw: "公司法",
    corporateDescription: "全面的商业法律服务，包括成立、治理和合规事务。",
    businessRegistration: "商业注册",
    corporateGovernance: "公司治理",
    complianceAdvisory: "合规咨询",
    commercialContracts: "商业合同",
    contractLaw: "合同法",
    contractDescription: "从起草到争议解决的各行业专业合同服务。",
    contractDrafting: "合同起草",
    agreementReview: "协议审查",
    negotiationSupport: "谈判支持",
    breachResolution: "违约解决",
    civilLitigation: "民事诉讼",
    litigationDescription: "具有周密准备和熟练法庭辩护的战略诉讼服务。",
    courtRepresentation: "法庭代理",
    caseStrategy: "案件策略",
    settlementNegotiation: "和解谈判",
    appealsProcess: "上诉程序",
    familyLaw: "家庭法",
    familyDescription: "以敏感性和专业知识为家庭事务提供富有同情心的法律支持。",
    divorceProceedings: "离婚程序",
    childCustody: "子女监护",
    matrimonialProperty: "婚姻财产",
    familyMediation: "家庭调解",
    landPropertyLaw: "土地和财产法",
    propertyDescription: "全面的房地产法律服务，包括交易、争议和产权事务。",
    propertyTransactions: "房地产交易",
    titleVerification: "产权验证",
    landDisputes: "土地争议",
    conveyancing: "房地产转让",
    countyNationalLaw: "县级和国家法律事务",
    governmentDescription: "政府和行政法律程序的专业代理。",
    administrativeLaw: "行政法",
    governmentRelations: "政府关系",
    publicPolicy: "公共政策",
    regulatoryCompliance: "法规合规",
    keyServices: "关键服务：",
    specializedConsultation: "需要专业领域的法律援助吗？我们在法律的各个领域提供咨询。",
    discussLegalNeeds: "讨论您的法律需求",
    
    // Contact
    contactTitle: "联系我们",
    contactSubtitle: "联系 Anna & Co Advocates 进行专业法律咨询",
    getInTouch: "取得联系",
    contactDescription: "准备讨论您的法律需求了吗？今天就联系 Anna & Co Advocates 进行专业法律咨询和代理。",
    phone: "电话",
    email: "邮箱",
    location: "位置",
    locationValue: "肯尼亚内罗毕CBD",
    officeHours: "办公时间",
    mondayFriday: "周一 - 周五：上午8:00 - 下午6:00",
    saturday: "周六：上午9:00 - 下午2:00",
    sunday: "周日：预约",
    
    // Footer
    practiceAreas: "实践领域",
    allRightsReserved: "版权所有。",
    legalDisclaimer: "本网站不构成法律建议。需要专业咨询以获得法律指导。",
  },
  
  de: {
    // Header
    home: "Startseite",
    about: "Über uns",
    services: "Dienstleistungen",
    contact: "Kontakt",
    languages: "Sprachen",
    
    // Languages
    english: "Englisch",
    kiswahili: "Kiswahili",
    french: "Französisch",
    spanish: "Spanisch",
    mandarin: "Mandarin",
    german: "Deutsch",
    
    // Hero
    heroTitle: "Anna & Co Advocates",
    heroSubtitle: "Professionelle Rechtsdienstleistungen",
    heroDescription: "Ihre vertrauenswürdigen Rechtspartner, die umfassende Vertretung in allen Rechtsbereichen bieten. Von Unternehmensangelegenheiten bis hin zu persönlichen rechtlichen Bedürfnissen liefern wir professionelle Exzellenz mit Integrität und Hingabe.",
    scheduleConsultation: "Beratung Vereinbaren",
    learnMore: "Mehr Erfahren",
    
    // About
    aboutTitle: "Über Anna & Co Advocates",
    aboutSubtitle: "Eine angesehene Rechtsanwaltskanzlei, die sich der Bereitstellung außergewöhnlicher Rechtsdienstleistungen mit unerschütterlicher Professionalität verschrieben hat",
    managingDirectorQuote: "Bei Anna & Co Advocates verstehen wir, dass rechtliche Herausforderungen überwältigend sein können. Deshalb verpflichten wir uns, nicht nur fachkundige Rechtsvertretung zu bieten, sondern auch die persönliche Aufmerksamkeit und klare Kommunikation, die Sie verdienen. Jeder Mandant ist wichtig, jeder Fall ist wichtig, und jedes Detail erhält unser vollständiges professionelles Engagement. Vertrauen Sie darauf, dass wir Sie auf Ihrem Rechtsweg begleiten.",
    managingDirector: "Geschäftsführerin",
    excellenceTitle: "Exzellenz in der Rechtspraxis",
    excellenceDescription1: "Anna & Co Advocates steht als Leuchtturm rechtlicher Exzellenz und bietet umfassende Rechtsdienstleistungen in verschiedenen Praxisbereichen. Unser Engagement für berufliche Integrität, akribische Aufmerksamkeit für Details und kundenorientierter Ansatz hebt uns in der Rechtslandschaft hervor.",
    excellenceDescription2: "Wir verstehen, dass Rechtsangelegenheiten nicht nur Fachwissen, sondern auch Empathie und klare Kommunikation erfordern. Unser Ansatz gewährleistet, dass jeder Mandant persönliche Aufmerksamkeit und strategische Beratung erhält, die auf seine einzigartigen Umstände zugeschnitten ist.",
    foundationTitle: "Unser Fundament",
    professionalExcellence: "Professionelle Exzellenz",
    integrity: "Integrität",
    clientFocus: "Kundenfokus",
    innovation: "Innovation",
    resultsDriven: "Ergebnisorientiert",
    credentialsTitle: "Berufliche Qualifikationen",
    llbDegree: "Bachelor der Rechtswissenschaften (LLB)",
    legalEducation: "Umfassende Rechtsausbildung",
    graduated: "Mit Auszeichnung abgeschlossen",
    admittedBar: "Zur Anwaltskammer zugelassen",
    licensedPractitioner: "Lizenzierter Rechtspraktiker",
    kenyaSchoolLaw: "Rechtsschule Kenia",
    verification: "Verifizierung",
    verifyCredentials: "Qualifikationen an der Rechtsschule Kenia verifizieren",
    approachTitle: "Unser Ansatz",
    approach1: "Umfassende Rechtsanalyse und Strategie",
    approach2: "Transparente Kommunikation bei jedem Schritt",
    approach3: "Maßgeschneiderte Lösungen für die Bedürfnisse jedes Mandanten",
    approach4: "Moderne Praxis mit bewährten Prinzipien",
    
    // Services
    servicesTitle: "Rechtsdienstleistungen",
    servicesSubtitle: "Umfassende Rechtsvertretung in mehreren Praxisbereichen mit professioneller Exzellenz und persönlicher Aufmerksamkeit",
    corporateLaw: "Gesellschaftsrecht",
    corporateDescription: "Umfassende Unternehmensrechtsdienstleistungen einschließlich Gründung, Governance und Compliance-Angelegenheiten.",
    businessRegistration: "Unternehmensregistrierung",
    corporateGovernance: "Unternehmensführung",
    complianceAdvisory: "Compliance-Beratung",
    commercialContracts: "Handelsverträge",
    contractLaw: "Vertragsrecht",
    contractDescription: "Fachkundige Vertragsdienstleistungen von der Erstellung bis zur Streitbeilegung in allen Branchen.",
    contractDrafting: "Vertragserstellung",
    agreementReview: "Vereinbarungsprüfung",
    negotiationSupport: "Verhandlungsunterstützung",
    breachResolution: "Vertragsverletzungsauflösung",
    civilLitigation: "Zivilprozess",
    litigationDescription: "Strategische Prozessdienstleistungen mit gründlicher Vorbereitung und geschickter Gerichtsvertretung.",
    courtRepresentation: "Gerichtsvertretung",
    caseStrategy: "Fallstrategie",
    settlementNegotiation: "Vergleichsverhandlung",
    appealsProcess: "Berufungsverfahren",
    familyLaw: "Familienrecht",
    familyDescription: "Mitfühlende Rechtsunterstützung für Familienangelegenheiten mit Sensibilität und Expertise.",
    divorceProceedings: "Scheidungsverfahren",
    childCustody: "Kindessorgerecht",
    matrimonialProperty: "Ehevermögen",
    familyMediation: "Familienvermittlung",
    landPropertyLaw: "Grund- und Eigentumsrecht",
    propertyDescription: "Umfassende Immobilienrechtsdienstleistungen einschließlich Transaktionen, Streitigkeiten und Eigentumsangelegenheiten.",
    propertyTransactions: "Immobilientransaktionen",
    titleVerification: "Eigentumsverifizierung",
    landDisputes: "Grundstücksstreitigkeiten",
    conveyancing: "Eigentumsübertragung",
    countyNationalLaw: "Bezirks- und Nationale Rechtsangelegenheiten",
    governmentDescription: "Spezialisierte Vertretung in staatlichen und verwaltungsrechtlichen Verfahren.",
    administrativeLaw: "Verwaltungsrecht",
    governmentRelations: "Regierungsbeziehungen",
    publicPolicy: "Öffentliche Politik",
    regulatoryCompliance: "Regulatorische Compliance",
    keyServices: "Hauptdienstleistungen:",
    specializedConsultation: "Benötigen Sie rechtliche Unterstützung in einem spezialisierten Bereich? Wir bieten Beratung in verschiedenen Rechtsbereichen.",
    discussLegalNeeds: "Ihre Rechtlichen Bedürfnisse Besprechen",
    
    // Contact
    contactTitle: "Kontaktieren Sie Uns",
    contactSubtitle: "Kontaktieren Sie Anna & Co Advocates für professionelle Rechtsberatung",
    getInTouch: "Kontakt Aufnehmen",
    contactDescription: "Bereit, Ihre rechtlichen Bedürfnisse zu besprechen? Kontaktieren Sie Anna & Co Advocates noch heute für professionelle Rechtsberatung und Vertretung.",
    phone: "Telefon",
    email: "E-Mail",
    location: "Standort",
    locationValue: "Nairobi CBD, Kenia",
    officeHours: "Öffnungszeiten",
    mondayFriday: "Montag - Freitag: 8:00 - 18:00",
    saturday: "Samstag: 9:00 - 14:00",
    sunday: "Sonntag: Nach Vereinbarung",
    
    // Footer
    practiceAreas: "Praxisbereiche",
    allRightsReserved: "Alle Rechte vorbehalten.",
    legalDisclaimer: "Diese Website stellt keine Rechtsberatung dar. Professionelle Beratung ist für rechtliche Anleitung erforderlich.",
  },
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState<Language>('en');

  const setLanguage = (language: Language) => {
    setCurrentLanguage(language);
  };

  const t = (key: string): string => {
    return translations[currentLanguage][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ currentLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
